### ISSUE TITLE
EthernetIP.cs GetBytes Unhandled Exception 

### ISSUE THREAD

**Issue by MugiwaraJAK** [MarvinThompson/HitachiEtherNetIP#139]
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=EIP
  StackTrace:
   at EIP_Lib.EIP.GetBytes(Byte[] data, Int32 start, Int32 length) in \HitachiEtherNetIP\Hitachi_EIP_DLL\Hitachi_EIP\EthernetIP.cs:line 1092
   at EIP_Lib.Browser.EIP_IO_Complete(EIP sender, EIPEventArg e) in \HitachiEtherNetIP\Hitachi_Browser_DLL\HitachiBrowserDLL\HitachiBrowser.cs:line 636
   at EIP_Lib.EIP.GetAttribute(ClassCode Class, Byte Attribute, Byte[] DataOut) in \HitachiEtherNetIP\Hitachi_EIP_DLL\Hitachi_EIP\EthernetIP.cs:line 766
   at EIP_Lib.Attributes`1.Get_Click(Object sender, EventArgs e) in \HitachiEtherNetIP\Hitachi_Browser_DLL\HitachiBrowserDLL\Attributes.cs:line 108
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.RunDialog(Form form)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at System.Windows.Forms.Form.ShowDialog()
   at H_EIP.TestEIP.cmdStartBrowser_Click(Object sender, EventArgs e) in \HitachiEtherNetIP\Hitachi_Browser_Test\H_EIP\TestEIP.cs:line 34
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at H_EIP.Program.Main() in \HitachiEtherNetIP\Hitachi_Browser_Test\H_EIP\Program.cs:line 16

**Comment by MugiwaraJAK** [comment]
This was resolved long ago. I do not remember the commit.
